version: '3'
services:
  web_server:
    build: web_server
    container_name: web_server
    ports:
      - ${BACKEND_PORT:-55301}:55301
    environment:
      RUST_LOG: ${RUST_LOG:-web_server=info}
      DATABASE_URL: postgres://${POSTGRES_USER:-non_manaka}:${POSTGRES_PASSWORD:-NonSugar}@db:5432/${POSTGRES_DB:-hccc_judge}
      CONTEST_BEGIN: ${CONTEST_BEGIN:-2022-11-13T19:00:00+09:00}
      CONTEST_END: ${CONTEST_END:-2022-11-13T21:00:00+09:00}
    depends_on:
      db:
        condition: service_healthy
    restart: always
    
  judge_server:
    build: judge_server
    container_name: judge_server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-non_manaka}:${POSTGRES_PASSWORD:-NonSugar}@db:5432/${POSTGRES_DB:-hccc_judge}
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-non_manaka}
      POSTGRES_DB: ${POSTGRES_DB:-hccc_judge}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-NonSugar}
    volumes:
      - db_store:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    restart: always
    healthcheck:
      test: psql -U ${POSTGRES_USER:-non_manaka} -d ${POSTGRES_DB:-hccc_judge} -c 'SELECT 1' || exit 1
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 10s

  test_runner_x8664:
    image: ghcr.io/humanccompilercontest/hccc_infra:test_runner_x8664-develop
    container_name: test_runner_x8664
    tty: true
    stdin_open: true
    profiles:
      - test_runner

  test_runner_riscv:
    image: ghcr.io/humanccompilercontest/hccc_infra:test_runner_riscv-develop
    container_name: test_runner_riscv
    tty: true
    stdin_open: true
    profiles:
      - test_runner

volumes:
  db_store:
