FROM rust:1.72.1
EXPOSE 55301

# Install cargo-watch
RUN cargo install cargo-watch

WORKDIR /app
COPY . .
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/app/target \
    cargo build

CMD ["/app/target/debug/web_server"]
