name: build / container image

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  build_image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        context: [judge_system]

    steps:
    - uses: actions/checkout@v3

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}
        flavor: |
          prefix=${{ format('{0}-', matrix.context }}

    - name: Set up Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to ghcr.io
      uses: docker/login-action@v2
      if: github.event_name == 'push'
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        context: ${{ matrix.context }}
        push: ${{ github.event_name == 'push' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha,scope=${{ matrix.context }}
        cache-to: type=gha,mode=max,scope=${{ matrix.context }}
